### ISSUE TITLE
How can I disable syntax highlighting?

### ISSUE THREAD

**Issue by batty098651** [Subtixx/vscode-mtalua#16]
How can I disable syntax highlighting? I want to use default one. I just care about code completion.

**Comment by Subtixx** [comment]
You have to edit the extension.ts and put the language code you want to use for syntax highlighting in here:
https://github.com/Subtixx/vscode-mtalua/blob/9e48c394072263a6af0656643516f6d5a64a24b0/src/extension.ts#L37

then just switch in vscode

**Comment by ingwardev** [comment]
i cant find that can you pass me precise path?

**Comment by batty098651** [comment]
edit; i found that but what i had to edit? i dont know

` vscode.languages.registerCompletionItemProvider({ scheme: "file", language: "lua" }, new functionProvider(context.extensionPath), "."); 
`
i changed it to this but it's same like before

editing language mode manually  does not change anything (mta lua i lua is the same)

**Comment by Subtixx** [comment]
I think thats correct. After doing that change from mtalua to lua just press SHIFT + P and type in "color theme" select "preferences: color theme" and select the appropriated color scheme. 

If its not working I need more information what is not working? Does the syntax highlight not change? Does the code completion not work?
