### ISSUE TITLE
color theme

### ISSUE THREAD

**Issue by yTp-Virus** [Subtixx/vscode-mtalua#21]
hello, i'm new in the github and idk how the issues tab work, but i'm having trouble with the DarkMTA theme, when i choose it, the VSCode Give me this Error

"Unable to load file:///c%3A/Users/mlice/.vscode/extensions/subtixx.mtasa-lua-2.4.0/themes/Monokai-MTA-Edit.tmTheme: Problems loading tmTheme file file:///c%3A/Users/mlice/.vscode/extensions/subtixx.mtasa-lua-2.4.0/themes/Monokai-MTA-Edit.tmTheme: Unable to read file 'c:\Users\mlice\.vscode\extensions\subtixx.mtasa-lua-2.4.0\themes\Monokai-MTA-Edit.tmTheme' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open 'c:\Users\mlice\.vscode\extensions\subtixx.mtasa-lua-2.4.0\themes\Monokai-MTA-Edit.tmTheme')
"

and it's strange cuz it was working fine weeks before, but yesterday i opened the lua file i was editing and it was on this weird color, and not with the blue color that i love ;-;.

print:

![image](https://user-images.githubusercontent.com/77742357/105202960-4aaf8f80-5b21-11eb-875e-90c2e33bccbf.png)

i tried everything and i can't fix it pls help ;-;

**Comment by yTp-Virus** [comment]
already fixed it.

**Comment by Subtixx** [comment]
The monokai theme is unsupported regardless since version 2.0.0 BETA. And was probably not updated since then.
