### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by SrMickael** [Subtixx/vscode-mtalua#24]
- Issue Type: `Bug`
- Extension Name: `mtasa-lua`
- Extension Version: `2.3.6`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.57.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by Subtixx** [comment]
Whats the issue here?

**Comment by Subtixx** [comment]
23 days without answer. Going to close this as there no further information.
