### ISSUE TITLE
Missing definitions

### ISSUE THREAD

**Issue by steventsvetkov** [Subtixx/vscode-mtalua#5]
Hey @Subtixx, I used to use MTALua on Sublime some time ago, I'm really happy to see it on VSCode as well. I've noticed there are some missing definitions you have documented in the defs files. Would you want some help with those?

**Comment by Subtixx** [comment]
The missing defs on the bottom are generated ones. No idea if they're still in MTA or even if they're client / server / shared.

Any help is appreciated. If I wouldn't want help, the extension would not be on GitHub 😀

**Comment by steventsvetkov** [comment]
Fair point :D

Maybe it would have been more appropriate to ask if you are currently doing those. I'll look into it and PR.

**Comment by Subtixx** [comment]
I'm not no
